sudo: false

addons:
  apt:
    packages:
      - doxygen
      - graphviz

language: c

compiler:
  - gcc
  - clang

before_script:
        - export LIBPREDICT_INSTALL_PATH="$PWD/libpredict-install"
        - mkdir -p $LIBPREDICT_INSTALL_PATH/lib
        - mkdir -p build

script:
        - cd build; cmake --version
        - cmake -D CMAKE_INSTALL_PREFIX=$LIBPREDICT_INSTALL_PATH ..
        - make
        - make test
        - make install
        - mkdir -p examples
        - cd examples
        - export COMPILER_FLAGS="-I $LIBPREDICT_INSTALL_PATH/include -L $LIBPREDICT_INSTALL_PATH/lib"
        - cmake -D CMAKE_C_FLAGS="$COMPILER_FLAGS" -D CMAKE_CXX_FLAGS="$COMPILER_FLAGS" ../../examples
        - make

notifications:
  irc:
    channels:
      - "irc.oftc.net#libpredict"
    use_notice: true
    skip_join: true

after_success:
  - $TRAVIS_BUILD_DIR/build/travis/publish-doxygen
